core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('api/v1/users/', include('users.urls')),
    path('api/v1/company/', include('company.urls')),
    path('api/v1/payment/', include('payment.urls'))
]

dashboard/urls.py
from django.urls import path

from .views import (
	home,
	users_view,
	user_update,
	companies_view,
	company_update,
	ad_update,
	admin_login,
	admin_logout,
	admin_update
)

app_name = 'dashboard'
urlpatterns = [
	path('', home, name='home'),
	path('users/', users_view, name='users'),
	path('user/<int:id>/', user_update, name='user-update'),
	path('companies/', companies_view, name='companies'),
	path('company/<int:id>/', company_update, name='company'),
	path('ad/<int:id>/', ad_update, name='ad-update'),
	path('login/', admin_login, name='login'),
	path('profile-update/', admin_update, name='profile-update'),
	path('logout/', admin_logout, name='logout')
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from django.urls import reverse

from users.models import Users
from company.models import Company, Ad



class AdminUpdateForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput, required=False)

	class Meta:
		model = Users
		fields = ['email','first_name','last_name']

	def save(self, commit=True):
		user = super().save(commit=False)
		password = self.cleaned_data.get('password')
		if password:
			user.set_password(password)
		
		user.save()
		return user


class UserUpdateForm(forms.ModelForm):
	class Meta:
		model = Users
		fields = ['email','password','first_name','last_name','telegram_name']
		

class CompanyForm(forms.ModelForm):
	class Meta:
		model = Company
		fields = ['user','ad','locations','name','website','launge','status']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		if 'user' in self.fields and 'ad' in self.fields:
			# user
			user = self.fields['user']
			user.widget = forms.widgets.TextInput()
			user.widget.attrs['readonly'] = True
			url = reverse('dashboard:user-update', args=[self.instance.user.id]) + f"?url={reverse('dashboard:company', args=[self.instance.id])}"
			user.widget.attrs['onclick'] = f"window.location.href='{url}'"

			# Ad
			ad = self.fields['ad']
			ad.widget = forms.widgets.TextInput()
			ad.widget.attrs['readonly'] = True
			url = reverse('dashboard:ad-update', args=[self.instance.ad.id]) + f"?url={reverse('dashboard:company', args=[self.instance.id])}"
			ad.widget.attrs['onclick'] = f"window.location.href='{url}'"

	
class AdForm(forms.ModelForm):
	class Meta:
		model = Ad
		fields = ('headline','description','ad_type','keywords','price','impressions','clicks',
				'click_rate','conversions','cost','cpc','cpa')


dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404
from datetime import datetime

from .forms import AdminUpdateForm, UserUpdateForm, CompanyForm, AdForm
from users.models import Users
from company.models import Company, Ad


@login_required
def home(request):
	""" home """
	user_count = Users.objects.filter(created_at=datetime.today().date()).count()
	company_count = Company.objects.filter(created_at=datetime.today().date()).count()
	return render(request, 'dashboard/home.html', {'user_count':user_count, 'company_count':company_count})

@login_required
def users_view(request):
	""" all users """
	search = request.GET.get("search")
	if search:
		users = Users.objects.filter(Q(email__contains=search) | Q(telegram_name__contains=search))
	else:
		users = Users.objects.all().order_by('-id')
	paginator = Paginator(users, 100)
	page_number = request.GET.get('page')
	page = paginator.get_page(page_number)
	return render(request, 'dashboard/users/view.html', {
		'page':page, 
		'search':search if search else '',
		'result':users.count()
	})

@login_required
def user_update(request, id):
	""" user update """
	try:
		user = Users.objects.get(id=id)
		url = request.GET.get('url')
		if request.method == "POST":
			form = UserUpdateForm(request.POST, instance=user)
			if form.is_valid():
				form.save()
				messages.success(request, f"{user.email} has been changed.")
				return redirect(url if url else "dashboard:users")
			messages.error(request, form.errors)
			return render(request, 'dashboard/users/update.html', {'form':form})
		return render(request, 'dashboard/users/update.html', {'form':UserUpdateForm(instance=user)})
	except Users.DoesNotExist:
		raise Http404

@login_required
def companies_view(request):
	""" all companies """
	search = request.GET.get("search")
	if search:
		company = Company.objects.filter(Q(name=search) | Q(user__email__contains=search), active=True)
	else:
		company = Company.objects.filter(active=True).order_by('-id')
	paginator = Paginator(company, 100)
	page_number = request.GET.get('page')
	page = paginator.get_page(page_number)
	return render(request, 'dashboard/company/view.html', {
		'page':page, 
		'search':search if search else '',
		'result':company.count()
	})

@login_required
def company_update(request, id):
	""" company update """
	try:
		company = Company.objects.get(id=id)
		if request.method == "POST":
			form = CompanyForm(request.POST, instance=company)
			if form.is_valid():
				form.save()
				messages.success(request, f"{company.name} has been changed.")
				return redirect("dashboard:companies")
			messages.error(request, form.errors)
			return render(request, 'dashboard/company/update.html', {'form':form})
		return render(request, 'dashboard/company/update.html', {'form':CompanyForm(instance=company)})
	except Company.DoesNotExist:
		raise Http404

@login_required
def ad_update(request, id):
	""" ad update """
	try:
		ad = Ad.objects.get(id=id)
		url = request.GET.get('url')
		if request.method == 'POST':
			form = AdForm(request.POST, instance=ad)
			if form.is_valid():
				form.save()
				messages.success(request, "ad has been changed.")
				return redirect(url if url else 'dashboard:home')
			messages.error(request, form.errors)
			return render(request, 'dashboard/company/ad-update.html', {'form':form})
		return render(request, 'dashboard/company/ad-update.html', {'form':AdForm(instance=ad)})
	except Ad.DoesNotExist:
		raise Http404

@login_required
def admin_update(request):
	""" admin user update """
	if request.method == 'POST':
		form = AdminUpdateForm(request.POST, instance=request.user)
		if form.is_valid():
			form.save()
			messages.success(request, 'The administrator profile has been changed.')
			return redirect('dashboard:home')
		messages.error(request, form.errors)
		return render(request, 'dashboard/admin/profile-update.html', {'form':form})
	return render(request, 'dashboard/admin/profile-update.html', {'form':AdminUpdateForm(instance=request.user)})

def admin_login(request):
	""" login """
	if request.method == "POST":
		email = request.POST['email']
		password = request.POST['password']
		user = authenticate(request, email=email, password=password)
		if user is not None and user.is_superuser:
			login(request, user)
			messages.success(request, 'Login successfully.')
			return redirect("dashboard:home")
		else:
			messages.error(request, 'Invalid username or password.')
	return render(request, 'dashboard/login.html')

@login_required
def admin_logout(request):
	""" logout """
	logout(request)
	return redirect('dashboard:login')

dashboard/templates/base.html
{% load static %}

{% url 'dashboard:home' as home %}
{% url 'dashboard:logout' as logout %}
{% url 'dashboard:profile-update' as profile_update %}
{% url 'dashboard:users' as users %}
{% url 'dashboard:companies' as companies %}

<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>

  <!-- boostrap css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- fontawesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav style="background: #111;" class="navbar navbar-expand-lg navbar-dark  fixed-top" id="mainNav" style="border: #111 1px solid;">
    <a class="navbar-brand" href="{{ home }}">Admin</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul  class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ home }}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
          <a class="nav-link" href="{{ users }}">
            <i class="fas fa-users"></i>
            <span class="nav-link-text">Users</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0 mr-lg-2">
            <div class="input-group">
              <input name='search' class="form-control" type="text" placeholder="Search for..." value="{{ search }}">
              <span class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
        </li>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ profile_update }}">Profile</a>
                <a class="dropdown-item" href="{{ logout }}">Logout</a>
              </div>
            </li>
          </ul>
        </div>
      </ul>
    </div>
  </nav>
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ home }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">{% block title %} Dashboard {% endblock title %}</li>
      </ol>
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-secondary alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    <div class="container">
      {% block content %}

      {% endblock content %}
    </div>
  </div>


    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Your Website {% now "Y" %}</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{{ logout }}">Logout</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- boostrap js -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>